all:
	@echo "files under current folder:"
	@ls
	@echo -e "\nfiles under ./abc folder:"
	@cd ./abc; \
	ls

aaa:
	@echo "files under current folder:"
	@ls
	@echo -e "\nfiles under ./abc folder:"
	@cd ./abc
	@ls

bbb:
	@echo "files under current folder:"
	@ls
	@echo -e "\nfiles under ./abc folder:"
	@cd ./abc; ls

